export const SHOP = {
  states: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Lakshadweep",
    "Puducherry",
  ],
  category: [
    {
      name: "clothing",
      sub: [
        { name: "accessories", iconClass: "icon-accessories" },
        { name: "pants", iconClass: "icon-pant" },
        { name: "shorts", iconClass: "icon-short" },
        { name: "jacket", iconClass: "icon-jacket" },
        { name: "dress", iconClass: "icon-dress" },
        { name: "suits", iconClass: "icon-suit" },
        { name: "shirt", iconClass: "icon-shirt" },
      ],
    },
    {
      name: "fruits",
      sub: [
        { name: "vegatables", iconClass: "icon-vegetable" },
        { name: "fruits", iconClass: "icon-fruit" },
        { name: "nut", iconClass: "icon-nut" },
        { name: "mushroom", iconClass: "icon-mushroom" },
      ],
    },
    {
      name: "electronic",
      sub: [
        { name: "air conditioning", iconClass: "icon-air-conditioning" },
        { name: "phone", iconClass: "icon-phone" },
        { name: "tv", iconClass: "icon-desktop" },
        { name: "speaker", iconClass: "icon-speaker" },
        { name: "fridge", iconClass: "icon-fridge" },
        { name: "fan", iconClass: "icon-fan" },
      ],
    },
    {
      name: "furniture",
      sub: [
        { name: "table", iconClass: "icon-table" },
        { name: "chair", iconClass: "icon-chair" },
        { name: "cabinet", iconClass: "icon-cabinet" },
        { name: "lamp", iconClass: "icon-lamp" },
        { name: "bed", iconClass: "icon-bed" },
      ],
    },
    {
      name: "cosmetics",
      sub: [
        { name: "lipstick", iconClass: "icon-lipstick" },
        { name: "powder", iconClass: "icon-powder" },
        { name: "perfume", iconClass: "icon-perfurm" },
        { name: "nail polish", iconClass: "icon-nail" },
        { name: "mascara", iconClass: "icon-mascara" },
      ],
    },
    {
      name: "medicines",
      sub: [
        { name: "sanitizers", iconClass: "icon-lipstick" },
        { name: "gloves", iconClass: "icon-powder" },
        { name: "tablets", iconClass: "icon-perfurm" },
        { name: "syrups", iconClass: "icon-nail" },
      ],
    },
  ],
};
